#!/bin/bash
# Dnsmasq Web Manager - 卸载脚本
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

[[ $EUID -ne 0 ]] && { echo -e "${RED}[ERROR]${NC} 请使用 root 权限运行"; exit 1; }

echo "========================================="
echo "  Dnsmasq Web Manager 卸载程序"
echo "========================================="
echo ""

# 1. 停止并禁用服务
log "停止服务..."
systemctl stop dnsmasq-web 2>/dev/null || true
systemctl disable dnsmasq-web 2>/dev/null || true
systemctl stop fix-resolv 2>/dev/null || true
systemctl disable fix-resolv 2>/dev/null || true

# 2. 删除 systemd 服务文件
log "删除 systemd 服务..."
rm -f /etc/systemd/system/dnsmasq-web.service
rm -f /etc/systemd/system/fix-resolv.service
rm -f /usr/local/bin/fix-resolv-conf.sh
systemctl daemon-reload

# 3. 删除 Web 应用
log "删除 Web 应用..."
rm -rf /opt/dnsmasq-web

# 4. 恢复 systemd-resolved
log "恢复 systemd-resolved..."
systemctl enable systemd-resolved 2>/dev/null || true
systemctl start systemd-resolved 2>/dev/null || true

# 5. 恢复 resolv.conf
log "恢复 resolv.conf..."
if [[ -f /etc/resolv.conf.bak ]]; then
    cp /etc/resolv.conf.bak /etc/resolv.conf
    log "已从备份恢复 resolv.conf"
else
    echo "# Generated by NetworkManager" > /etc/resolv.conf
    echo "nameserver 127.0.0.53" >> /etc/resolv.conf
    warn "已重置 resolv.conf（无备份）"
fi

# 6. 卸载 dnsmasq（可选）
read -p "是否同时卸载 dnsmasq？[y/N] " choice
if [[ "$choice" =~ ^[Yy]$ ]]; then
    log "卸载 dnsmasq..."
    systemctl stop dnsmasq 2>/dev/null || true
    apt-get remove -y dnsmasq 2>/dev/null || true
    rm -f /etc/dnsmasq.conf /etc/dnsmasq.hosts
    rm -rf /etc/dnsmasq.d
    log "dnsmasq 已卸载"
else
    log "保留 dnsmasq"
fi

echo ""
echo "========================================="
echo -e "${GREEN}  卸载完成！${NC}"
echo "========================================="
